service: lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /api
          method: GET
          cors: true

  todos:
    handler: src/todos.handler
    events:
      - http:
          path: /todos
          method: GET

  todo:
    handler: src/todo.handler
    events:
      - http:
          path: /todo/{id}
          method: GET
          request:
            parameters:
              id: true
